MODEL:
  NAME: 'efficientnet-b7'
#  DEVICE_ID: '0'
  LOSS_WAY: 'all'

DATASETS:
  HARD_AUG: 'simple'
  BATCH_SIZE: 24
  WORKERS: 4

INPUT:
  SIZE_TRAIN: '[224, 224]'
  SIZE_TEST: '[456, 456]'
  GRAY_RPO: 0.05
  RE_PROB: 0.5
SOLVER:
  TYPE: 'warmup_cos'
  STEPS: [15, 25]
  MAX_EPOCHS: 120
  WARMUP_EPOCHS: 2
  BASE_LR: 0.001
  CENTER_LR: 0.2
  CENTER_LOSS_WEIGHT: 0.0003
  COSINE_MARGIN: 0.1
  COSINE_SCALE: 40
  IMS_PER_BATCH: 4
